fruits = {"apple", "banana", "cherry"}
fruits.add("orange")
print(fruits)
fruits.remove("banana")
print(fruits)
fruits.discard("grape")
print(fruits)
remove_item = fruits.pop()
print(remove_item)
print(fruits)
fruits.clear()
print(fruits)